server:
  port: 8091
  
logging:
  file:
    name: log/dsa360.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dsa360prod?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        connection:
          provider-disables-autocommit: false

  mail:
    host: smtp.gmail.com
    password: sevdtuwbsgjxecqy
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: dsa360system@gmail.com

management:
  endpoints:
    web: 
      exposure:
        include: "*"
      base-path: /actuator 
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
